
-- USER SQL
CREATE USER "PROY_SEMESTRAL" IDENTIFIED BY "Semestral1234"
DEFAULT TABLESPACE "SYSAUX"
TEMPORARY TABLESPACE "TEMP";


-- QUOTAS
ALTER USER "PROY_SEMESTRAL" QUOTA UNLIMITED ON "DATA";
ALTER USER "PROY_SEMESTRAL" QUOTA UNLIMITED ON "SYSAUX";

-- ROLES
GRANT "CONNECT" TO "PROY_SEMESTRAL" ;
GRANT "RESOURCE" TO "PROY_SEMESTRAL" ;

-- SYSTEM PRIVILEGES
GRANT CREATE ROLE TO "PROY_SEMESTRAL" ;
GRANT CREATE TRIGGER TO "PROY_SEMESTRAL" ;
GRANT CREATE MATERIALIZED VIEW TO "PROY_SEMESTRAL" ;
GRANT CREATE INDEXTYPE TO "PROY_SEMESTRAL" ;
GRANT CREATE VIEW TO "PROY_SEMESTRAL" ;
GRANT CREATE SESSION TO "PROY_SEMESTRAL" ;
GRANT DELETE ANY TABLE TO "PROY_SEMESTRAL" ;
GRANT CREATE TABLE TO "PROY_SEMESTRAL" ;
GRANT CREATE PUBLIC SYNONYM TO "PROY_SEMESTRAL" ;
GRANT CREATE SYNONYM TO "PROY_SEMESTRAL" ;
GRANT CREATE SEQUENCE TO "PROY_SEMESTRAL" ;
GRANT CREATE USER TO "PROY_SEMESTRAL" ;
GRANT UPDATE ANY TABLE TO "PROY_SEMESTRAL" ;
GRANT COMMENT ANY TABLE TO "PROY_SEMESTRAL" ;
GRANT DROP PUBLIC SYNONYM TO "PROY_SEMESTRAL" ;
GRANT INSERT ANY TABLE TO "PROY_SEMESTRAL" ;
GRANT CREATE PROCEDURE TO "PROY_SEMESTRAL" ;
GRANT SELECT ANY TABLE TO "PROY_SEMESTRAL";