---> 2.2.1	RESUMEN DEL TOTAL DE POSTULANTES A LA BECA POR REGIÓN 

SELECT
        RE.NOM_REGION REGION,
        COUNT(PO.ID_POSTULANTE) TOTAL_POSTULANTES
FROM REGION RE
JOIN COMUNA CO ON RE.ID_REG = CO.ID_REG
JOIN POSTULANTE PO ON CO.ID_COMUNA = PO.ID_COMUNA
GROUP BY RE.NOM_REGION,RE.ID_REG
ORDER BY RE.ID_REG;
/

---> consultas con el usuario admin
---> 2.2.2	DETALLE DE POSTULANTES A LA BECA
SELECT
    SUBSTR(RUT,1,2)||TO_CHAR(FECH_NACI,'DD')||SUBSTR(RUT,3)||SUBSTR(TO_CHAR(FECH_NACI,'Month'),1,2)||'-'||DV_RUT||SUBSTR(TO_CHAR(FECH_NACI,'YY'),1,1) "RUN POSTULANTE",
    PNOMBRE||' '||SNOMBRE||' '||APPATERNO||' '||APMATERNO "NOMBRE POSTULANTE",
    FECHA_POST "FECHA POSTULACION",
    EC.DESCRIPCION "EST.CIVIL",
    PO.DIRECCION||', '||CO.NOM_COMUNA DIRECCION,
    AP.SUBESP_MEDICA "SUBESPECIALIDAD A LA QUE POSTULA",
    AP.NOM_INSTI_ACAD "INSTITUCIÓN ACADÉMICA",
    INITCAP(RE.NOM_REGION) CIUDAD,
    INITCAP(PA.NOM_PAIS) "PAÍS"
FROM POSTULANTE PO
JOIN FORMULARIO FO 
    ON PO.ID_POSTULANTE = FO.ID_POSTULANTE
JOIN EST_CIVIL EC 
    ON EC.ID_ESTCIVIL = PO.ID_ESTCIVIL
JOIN COMUNA CO 
    ON PO.ID_COMUNA = CO.ID_COMUNA
JOIN ANTEC_POSTULACION AP 
    ON FO.ID_ANTECEDENTES = AP.ID_ANTECEDENTES
JOIN REGION RE
    ON AP.ID_REG = RE.ID_REG
JOIN PAIS PA
    ON RE.ID_PAIS = PA.ID_PAIS
/
---> consultas con el usuario DESARROLLADOR 1 POR MEDIO DE SINONIMOS
---> 2.2.2	DETALLE DE POSTULANTES A LA BECA
SELECT
    SUBSTR(RUT,1,2)||TO_CHAR(FECH_NACI,'DD')||SUBSTR(RUT,3)||SUBSTR(TO_CHAR(FECH_NACI,'Month'),1,2)||'-'||DV_RUT||SUBSTR(TO_CHAR(FECH_NACI,'YY'),1,1) "RUN POSTULANTE",
    PNOMBRE||' '||SNOMBRE||' '||APPATERNO||' '||APMATERNO "NOMBRE POSTULANTE",
    FECHA_POST "FECHA POSTULACION",
    EC.DESCRIPCION "EST.CIVIL",
    PO.DIRECCION||', '||CO.NOM_COMUNA DIRECCION,
    AP.SUBESP_MEDICA "SUBESPECIALIDAD A LA QUE POSTULA",
    AP.NOM_INSTI_ACAD "INSTITUCIÓN ACADÉMICA",
    INITCAP(RE.NOM_REGION) CIUDAD,
    INITCAP(PA.NOM_PAIS) "PAÍS"
FROM SYN_POST PO
JOIN SYN_FORM FO 
    ON PO.ID_POSTULANTE = FO.ID_POSTULANTE
JOIN SYN_ECIVIL EC 
    ON EC.ID_ESTCIVIL = PO.ID_ESTCIVIL
JOIN SYN_COMUNA CO 
    ON PO.ID_COMUNA = CO.ID_COMUNA
JOIN SYN_APOST AP 
    ON FO.ID_ANTECEDENTES = AP.ID_ANTECEDENTES
JOIN SYN_REG RE
    ON AP.ID_REG = RE.ID_REG
JOIN SYN_PAIS PA
    ON RE.ID_PAIS = PA.ID_PAIS
/

---> consultas con el usuario admin
----> 2.2.3 PUNTAJES OBTENIDOS POR CADA POSTULANTE A LA BECA
-- CREATE VIEW PUNTAJES AS 
SELECT
    TO_CHAR(RUT,'99G999G999')||'-'||DV_RUT "RUN POSTULANTE",
    INITCAP(PNOMBRE||' '||SNOMBRE||' '||APPATERNO||' '||APMATERNO) "NOMBRE POSTULANTE",
    TRUNC(MONTHS_BETWEEN(SYSDATE,FECH_NACI)/12) EDAD, 
    CE.PUNTAJE "PTJE. EDAD",
    INITCAP(EC.DESCRIPCION) "EST. CIVIL",
    CEC.PUNTAJE "PTJE. EST. CIVIL",
    FO.PUEBLO_INDIGENA "PUEBLO IND. ORIG.",
    NVL(CPO.PUNTAJE,0) "PTJE. PUEBLO IND. ORIG.",
    NVL(CRE.PUNTAJE,0) "PTJE. ZONA EXTREMA",
    CAN.PUNTAJE "PTJE. ANTEC. ACAD.",
    NVL(CEL.PUNTAJE,5) "PTJE. EXP. LABORAL",
    CAD.PUNTAJE "PTJE. DOCENCIA/INVEST.",
    COE.PUNTAJE "PTJE. OBJETIVO ESTUDIO",
    CDI.PUNTAJE "PTJE. INTERES",
    CRP.PUNTAJE "PTJE. RETRIB",
    NVL(CR.PUNTAJE,0) "PTJE. RANK. EDUC. EXTRANJERA",
    CE.PUNTAJE + CEC.PUNTAJE + NVL(CPO.PUNTAJE,0) + NVL(CRE.PUNTAJE,0) + CAN.PUNTAJE +
    NVL(CEL.PUNTAJE,5) + CAD.PUNTAJE + COE.PUNTAJE + CDI.PUNTAJE + CRP.PUNTAJE + NVL(CR.PUNTAJE,0) "PTJE. TOTAL"

FROM POSTULANTE PO

JOIN CRITERIO_EDAD CE
    ON TRUNC(MONTHS_BETWEEN(SYSDATE,FECH_NACI)/12) BETWEEN CE.RANGO_MIN AND CE.RANGO_MAX
JOIN EST_CIVIL EC
    ON PO.ID_ESTCIVIL = EC.ID_ESTCIVIL
JOIN CRITERIO_ESTADO_CIVIL CEC
    ON EC.DESCRIPCION IN CEC.TIPO
JOIN FORMULARIO FO
    ON PO.ID_POSTULANTE = FO.ID_POSTULANTE
LEFT JOIN CRITERIO_PUEBLO_ORIGIN CPO
    ON FO.PUEBLO_INDIGENA IN CPO.NOMBRE
JOIN COMUNA CO
    ON CO.ID_COMUNA = PO.ID_COMUNA
JOIN REGION RE
    ON CO.ID_REG = RE.ID_REG
LEFT JOIN CRITERIO_REG_EXTREMA CRE
    ON RE.NOM_REGION IN CRE.REGION
JOIN GRADOS_ACAD GA
    ON FO.ID_GRADOS = GA.ID_GRADOS
JOIN CRITERIO_ANT_NOTAS CAN
    ON GA.NOTA BETWEEN CAN.RANGO_MIN AND CAN.RANGO_MAX
JOIN EXP_LABORAL EL
    ON FO.ID_EXP = EL.ID_EXP
LEFT JOIN CRITERIO_EXP_LABORAL CEL
    ON TRUNC(MONTHS_BETWEEN(EL.FECHA_TERMINO,EL.FEC_INICIO)/12) IN CEL.RANGO
JOIN LINEA_INVES LI
    ON FO.ID_INVEST = LI.ID_INVEST
JOIN CRITERIO_ACT_DOCENCIA CAD
    ON LI.RANGO IN CAD.TIPO
JOIN OBJE_POSTULACION OP
    ON FO.ID_OBJE = OP.ID_OBJE
JOIN CRITERIO_OBJ_ESTUDIO COE
    ON OP.RANGO IN COE.TIPO
JOIN CRITERIO_DECLA_INTERES CDI
    ON FO.INTERES IN CDI.TIPO
JOIN CRITERIO_RETRI_POSTULANTE CRP
    ON FO.RETRIBUCION IN CRP.TIPO
JOIN ANTEC_POSTULACION AP
    ON FO.ID_ANTECEDENTES = AP.ID_ANTECEDENTES
LEFT JOIN CRITERIO_RANKING CR
    ON AP.RANKING_INSTITUCION1 BETWEEN CR.RANGO_MIN AND CR.RANGO_MAX
;
/

---> consultas con el usuario DESARROLLADOR 2
----> 2.2.3 PUNTAJES OBTENIDOS POR CADA POSTULANTE A LA BECA
CREATE VIEW PUNTAJES AS 
SELECT
    TO_CHAR(RUT,'99G999G999')||'-'||DV_RUT "RUN POSTULANTE",
    INITCAP(PNOMBRE||' '||SNOMBRE||' '||APPATERNO||' '||APMATERNO) "NOMBRE POSTULANTE",
    TRUNC(MONTHS_BETWEEN(SYSDATE,FECH_NACI)/12) EDAD, 
    CE.PUNTAJE "PTJE. EDAD",
    INITCAP(EC.DESCRIPCION) "EST. CIVIL",
    CEC.PUNTAJE "PTJE. EST. CIVIL",
    FO.PUEBLO_INDIGENA "PUEBLO IND. ORIG.",
    NVL(CPO.PUNTAJE,0) "PTJE. PUEBLO IND. ORIG.",
    NVL(CRE.PUNTAJE,0) "PTJE. ZONA EXTREMA",
    CAN.PUNTAJE "PTJE. ANTEC. ACAD.",
    NVL(CEL.PUNTAJE,5) "PTJE. EXP. LABORAL",
    CAD.PUNTAJE "PTJE. DOCENCIA/INVEST.",
    COE.PUNTAJE "PTJE. OBJETIVO ESTUDIO",
    CDI.PUNTAJE "PTJE. INTERES",
    CRP.PUNTAJE "PTJE. RETRIB",
    NVL(CR.PUNTAJE,0) "PTJE. RANK. EDUC. EXTRANJERA",
    CE.PUNTAJE + CEC.PUNTAJE + NVL(CPO.PUNTAJE,0) + NVL(CRE.PUNTAJE,0) + CAN.PUNTAJE +
    NVL(CEL.PUNTAJE,5) + CAD.PUNTAJE + COE.PUNTAJE + CDI.PUNTAJE + CRP.PUNTAJE + NVL(CR.PUNTAJE,0) "PTJE. TOTAL"

FROM POSTULANTE PO

JOIN CRITERIO_EDAD CE
    ON TRUNC(MONTHS_BETWEEN(SYSDATE,FECH_NACI)/12) BETWEEN CE.RANGO_MIN AND CE.RANGO_MAX
JOIN EST_CIVIL EC
    ON PO.ID_ESTCIVIL = EC.ID_ESTCIVIL
JOIN CRITERIO_ESTADO_CIVIL CEC
    ON EC.DESCRIPCION IN CEC.TIPO
JOIN FORMULARIO FO
    ON PO.ID_POSTULANTE = FO.ID_POSTULANTE
LEFT JOIN CRITERIO_PUEBLO_ORIGIN CPO
    ON FO.PUEBLO_INDIGENA IN CPO.NOMBRE
JOIN COMUNA CO
    ON CO.ID_COMUNA = PO.ID_COMUNA
JOIN REGION RE
    ON CO.ID_REG = RE.ID_REG
LEFT JOIN CRITERIO_REG_EXTREMA CRE
    ON RE.NOM_REGION IN CRE.REGION
JOIN GRADOS_ACAD GA
    ON FO.ID_GRADOS = GA.ID_GRADOS
JOIN CRITERIO_ANT_NOTAS CAN
    ON GA.NOTA BETWEEN CAN.RANGO_MIN AND CAN.RANGO_MAX
JOIN EXP_LABORAL EL
    ON FO.ID_EXP = EL.ID_EXP
LEFT JOIN CRITERIO_EXP_LABORAL CEL
    ON TRUNC(MONTHS_BETWEEN(EL.FECHA_TERMINO,EL.FEC_INICIO)/12) IN CEL.RANGO
JOIN LINEA_INVES LI
    ON FO.ID_INVEST = LI.ID_INVEST
JOIN CRITERIO_ACT_DOCENCIA CAD
    ON LI.RANGO IN CAD.TIPO
JOIN OBJE_POSTULACION OP
    ON FO.ID_OBJE = OP.ID_OBJE
JOIN CRITERIO_OBJ_ESTUDIO COE
    ON OP.RANGO IN COE.TIPO
JOIN CRITERIO_DECLA_INTERES CDI
    ON FO.INTERES IN CDI.TIPO
JOIN CRITERIO_RETRI_POSTULANTE CRP
    ON FO.RETRIBUCION IN CRP.TIPO
JOIN ANTEC_POSTULACION AP
    ON FO.ID_ANTECEDENTES = AP.ID_ANTECEDENTES
LEFT JOIN CRITERIO_RANKING CR
    ON AP.RANKING_INSTITUCION1 BETWEEN CR.RANGO_MIN AND CR.RANGO_MAX
;
/
