--CREAR SINONIMOS EN PROY_SEMESTRAL 

CREATE PUBLIC SYNONYM SYN_APOST
FOR PROY_SEMESTRAL.ANTEC_POSTULACION;

CREATE PUBLIC SYNONYM SYN_COMUNA
FOR PROY_SEMESTRAL.COMUNA;

CREATE PUBLIC SYNONYM SYN_CRIT_ACT_DOC
FOR PROY_SEMESTRAL.CRITERIO_ACT_DOCENCIA;

CREATE PUBLIC SYNONYM SYN_CRIT_ANT_NOTAS
FOR PROY_SEMESTRAL.CRITERIO_ANT_NOTAS;

CREATE PUBLIC SYNONYM SYN_CRIT_DEC_INT
FOR PROY_SEMESTRAL.CRITERIO_DECLA_INTERES;

CREATE PUBLIC SYNONYM SYN_CRIT_EDAD
FOR PROY_SEMESTRAL.CRITERIO_EDAD;

CREATE PUBLIC SYNONYM SYN_CRIT_ECIVIL
FOR PROY_SEMESTRAL.CRITERIO_ESTADO_CIVIL;

CREATE PUBLIC SYNONYM SYN_CRIT_EXPLABORAL
FOR PROY_SEMESTRAL.CRITERIO_EXP_LABORAL;

CREATE PUBLIC SYNONYM SYN_CRIT_OBJ_EST
FOR PROY_SEMESTRAL.CRITERIO_OBJ_ESTUDIO;

CREATE PUBLIC SYNONYM SYN_CRIT_PORIGIN
FOR PROY_SEMESTRAL.CRITERIO_PUEBLO_ORIGIN;

CREATE PUBLIC SYNONYM SYN_CRIT_RANK
FOR PROY_SEMESTRAL.CRITERIO_RANKING;

CREATE PUBLIC SYNONYM SYN_CRIT_REG_EXT
FOR PROY_SEMESTRAL.CRITERIO_REG_EXTREMA;

CREATE PUBLIC SYNONYM SYN_CRIT_RET_POST
FOR PROY_SEMESTRAL.CRITERIO_RETRI_POSTULANTE;

CREATE PUBLIC  SYNONYM SYN_ECIVIL
FOR PROY_SEMESTRAL.EST_CIVIL;

CREATE PUBLIC  SYNONYM SYN_EST_ESPE
FOR PROY_SEMESTRAL.EST_ESPECIALIZACION;

CREATE PUBLIC  SYNONYM SYN_EST_SEC
FOR PROY_SEMESTRAL.ESTUDIO_SEC;

CREATE PUBLIC  SYNONYM SYN_EST_UNIV
FOR PROY_SEMESTRAL.ESTUDIO_UNI;

CREATE PUBLIC  SYNONYM SYN_EXPLABORAL
FOR PROY_SEMESTRAL.EXP_LABORAL;

CREATE PUBLIC  SYNONYM SYN_FORM
FOR PROY_SEMESTRAL.FORMULARIO;

CREATE PUBLIC  SYNONYM SYN_GACAD
FOR PROY_SEMESTRAL.GRADOS_ACAD;

CREATE PUBLIC  SYNONYM SYN_IDIOMA
FOR PROY_SEMESTRAL.IDIOMA;

CREATE PUBLIC  SYNONYM SYN_LINVES
FOR PROY_SEMESTRAL.LINEA_INVES;

CREATE PUBLIC  SYNONYM SYN_OBJEPOST
FOR PROY_SEMESTRAL.OBJE_POSTULACION;

CREATE PUBLIC  SYNONYM SYN_PAIS
FOR PROY_SEMESTRAL.PAIS;

CREATE PUBLIC  SYNONYM SYN_POST
FOR PROY_SEMESTRAL.POSTULANTE;

CREATE PUBLIC  SYNONYM SYN_REG
FOR PROY_SEMESTRAL.REGION;

CREATE PUBLIC  SYNONYM SYN_TPROF
FOR PROY_SEMESTRAL.TITULO_PROF;




